version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0
  docker: circleci/docker@1.0.0

workflows:
  deploy:
    jobs:
      - docker/publish:
          executor:
              image: circleci/node
              name: docker/docker
              tag: boron-browsers
            image: my/image
            remote-docker-dlc: true
            tag: my-tag
            use-remote-docker: true
          # image: docker-part3-task2
          # name: docker/docker
          # tag: docker-part3-task2/web
          # registry: registry.heroku.com
