version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0
  docker: circleci/docker@1.0.0

jobs:
  buildaa:
    steps:
      - docker/publish:
        image: docker-part3-task2/web
        deploy: false


workflows:
  deploy:
    jobs:
      - buildaa



