version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0
  docker: circleci/docker@1.0.0

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: anttiheimonen/testing
          tag: 'latest'


# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/push-docker-image:
