version: 2.1

orbs:
  heroku: circleci/heroku@1.2.0
  docker: circleci/docker@1.0.0

jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/publish:
          deploy: false
          image: docker-part3-task2/web


workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only




